routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\StockController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\AttributeController;
use App\Http\Controllers\Admin\CartController;
use App\Http\Controllers\Admin\SliderController;

Route::get('/', [SiteController::class, 'index'])->name('index');
Route::get('/products/{product}', [SiteController::class, 'product'])->name('product');
Route::get('/cart', [SiteController::class, 'cart'])->name('cart');
Route::get('/add-to-cart/{product}', [SiteController::class, 'addToCart'])->name('add.to.cart')->middleware('auth');
Route::patch('update-cart', [SiteController::class, 'update'])->name('update.cart');
Route::delete('remove-from-cart', [SiteController::class, 'remove'])->name('remove.from.cart');


Route::get('/home', [SiteController::class, 'home'])->name('home')->middleware('auth');

Route::get('/search', [\App\Http\Controllers\SiteController::class, 'search'])->name('search');

// Route::group(
//     [
//         'middleware' => ['auth', 'admin'],
//         'name' => 'admin.',
//         'prefix' => 'admin'
//     ],
//     function () {
//         Route::get('/', [AdminController::class, 'index'])->name('index');
//         Route::resource('users', [UserController::class]);
//     }
// );
// 'auth', 'admin'
Route::middleware(['auth', 'admin'])->name('admin.')->prefix('admin')->group(function () {
    Route::get('/', [AdminController::class, 'index'])->name('index');
    Route::resource('users', UserController::class);
    Route::get('categories/slug', [CategoryController::class, 'generateSlug'])->name('categories.slug');
    Route::resource('categories', CategoryController::class);
    Route::get('products/slug', [ProductController::class, 'generateSlug'])->name('products.slug');
    Route::resource('products', ProductController::class);
    Route::resource('stocks', StockController::class);
    Route::resource('attributes', AttributeController::class);
    Route::resource('coupons', CouponController::class);

    //orders
    Route::post('/orders/{order}/status', [OrderController::class, 'UpdateStatus'])->name('orders.status');
    Route::post('/orders/{order}/products', [OrderController::class, 'AddProduct'])->name('orders.products');
    Route::delete('/orders/{order}/products', [OrderController::class, 'removeProduct'])->name('orders.removeProducts');
    Route::get('/orders/{order}/{orderid}/quantity', [OrderController::class, 'editQuantity'])->name('orders.quantity.edit');
    Route::post('/orders/{order}/{orderid}/quantity', [OrderController::class, 'updateQuantity'])->name('orders.quantity.update');

    Route::resource('orders', OrderController::class)->except(['destroy']);
    Route::resource('sliders', SliderController::class);

    Route::resource('carts', CartController::class);
});

app/Models/Attribute.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Attribute extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'description'];

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }
}

app/Http/Controllers/Admin/AttributeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Attribute;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class AttributeController extends Controller
{

    public function index(): View
    {
        $attributes = Attribute::paginate(12);
        return view('admin.attributes.index', compact('attributes'));
    }

    public function create(): View
    {
        return view('admin.attributes.create');
    }

    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'name'          => ['required'],
            'description'   => ['nullable'],
        ]);

        Attribute::create([
            'name'  => $request->name,
            'description'   => clean($request->description),
        ]);

        return redirect()->route('admin.attributes.index')->with('success', 'Attribute Added Successfully');
    }


    public function edit(Attribute $attribute): View
    {
        return view('admin.attributes.edit', compact('attribute'));
    }

    public function update(Request $request, Attribute $attribute): RedirectResponse
    {
        $request->validate([
            'name'          => ['required'],
            'description'   => ['nullable'],
        ]);

        $attribute->update([
            'name'  => $request->name,
            'description'   => clean($request->description),
        ]);

        return redirect()->route('admin.attributes.index')->with('success', 'Attribute Updated Successfully');
    }


    public function destroy(Attribute $attribute)
    {
        $attribute->delete();

        return redirect()->route('admin.attributes.index')->with('success', 'Attribute Deleted Successfully');
    }
}

resources/views/admin/attributes/create.blade.php
@extends('adminlte::page')

@section('title','Add Attribute')

@section('content')

<x-alert/>

<x-editor field="description"/>

<div class="card">
    <div class="card-header">
        <h3 class="card-title text-bold" style="font-size: 1.3rem; line-height: 1.5;">
            Add Attribute
        </h3>

        <div class="card-tools">
            <a href="{{ route('admin.attributes.index') }}" class="btn-sm btn-primary">
                Show All Attributes
            </a>
        </div>
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route('admin.attributes.store') }}" enctype="multipart/form-data" >

            @csrf

            <x-input
            field="name"
            text="Name"
            />

            <x-input
            field="description"
            text="Description"
            type="textarea"
            />

        <button type="submit" class="btn-sm btn-primary">
            <i class="fas fa-fw fa-save mr-2"></i>
            <span>Save</span>
        </button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/attributes/edit.blade.php
@extends('adminlte::page')

@section('title','Add Attribute')

@section('content')

<x-alert/>

<x-editor field="description"/>


<div class="card">
    <div class="card-header">
        <h3 class="card-title text-bold" style="font-size: 1.3rem; line-height: 1.5;">
            Add Attribute
        </h3>

        <div class="card-tools">
            <a href="{{ route('admin.attributes.index') }}" class="btn-sm btn-primary">
                Show All Attributes
            </a>
        </div>
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route('admin.attributes.update', $attribute) }}" enctype="multipart/form-data" >

            @csrf
            @method('PUT')

            <x-input
            field="name"
            text="Name"
            :current="$attribute->name"
            />

            <x-input
            field="description"
            text="Description"
            type="textarea"
            :current="$attribute->description"
            />

        <button type="submit" class="btn-sm btn-primary">
            <i class="fas fa-fw fa-save mr-2"></i>
            <span>Save</span>
        </button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/attributes/index.blade.php
@extends('adminlte::page')

@section('title', 'Product attributes')

@section('content')

<x-alert/>
<x-delete/>

    <div class="card">
        <div class="card-header">

            <h3 class="card-title text-bold" style="font-size: 1.3rem; line-height: 1.5">Product Attributes</h3>
            <div class="card-tools">
              <a href="{{route('admin.attributes.create')}}" class="btn-sm btn-primary" >Add attributes</a>
            </div>
            
        </div>
        <div class="card-body p-0">

            @if (count($attributes) > 0)              
           
            <table class="table table-bordered table-striped">
                <thead class="thead-dark bg-info">
                    <tr>
                        <td>ID</td>
                        <td>Attribute Name</td>
                        <td>Description</td>
                        <td>Actions</td>
                    </tr>
                </thead>

                <tbody>
                    
                    @foreach ($attributes as $attribute )

                    <tr>
                        <td>{{ $attribute->id }}</td>

                        <td>{{ $attribute->name }}</td>

                        <td>{{ strip_tags($attribute->description) }}</td>

                        <td>

                            <a 
                                href="{{ route('admin.attributes.edit', $attribute->id) }}" 
                                class="btn-sm btn-secondary mr-2">
                                Edit Attribute
                            </a>
                            
                            <a href="#" onclick="confirmDelete({{ $attribute->id }})" class="btn-sm btn-danger" > Delete 
                            </a>

                            <form id="delete-form-{{ $attribute->id }}" action="{{ route('admin.attributes.destroy', $attribute) }}" method="POST">

                            @csrf    
                            @method('DELETE')

                            </form>
                            
                        </td>
                    </tr>
                    
                    @endforeach
                    
                </tbody>
            </table>
            
            @else

            <div class="alert alert-warning mb-0 text-center">
                No more attributes available !
            </div>

            @endif
            
        </div>
        @if ($attributes->perpage() < $attributes->total() )
            <div class="card-footer">
                {{ $attributes->links() }}
            </div>
        @endif
    </div>
@endsection