routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\StockController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\AttributeController;
use App\Http\Controllers\Admin\CartController;
use App\Http\Controllers\Admin\SliderController;

Route::get('/', [SiteController::class, 'index'])->name('index');
Route::get('/products/{product}', [SiteController::class, 'product'])->name('product');
Route::get('/cart', [SiteController::class, 'cart'])->name('cart');
Route::get('/add-to-cart/{product}', [SiteController::class, 'addToCart'])->name('add.to.cart')->middleware('auth');
Route::patch('update-cart', [SiteController::class, 'update'])->name('update.cart');
Route::delete('remove-from-cart', [SiteController::class, 'remove'])->name('remove.from.cart');


Route::get('/home', [SiteController::class, 'home'])->name('home')->middleware('auth');

Route::get('/search', [\App\Http\Controllers\SiteController::class, 'search'])->name('search');

// Route::group(
//     [
//         'middleware' => ['auth', 'admin'],
//         'name' => 'admin.',
//         'prefix' => 'admin'
//     ],
//     function () {
//         Route::get('/', [AdminController::class, 'index'])->name('index');
//         Route::resource('users', [UserController::class]);
//     }
// );
// 'auth', 'admin'
Route::middleware(['auth', 'admin'])->name('admin.')->prefix('admin')->group(function () {
    Route::get('/', [AdminController::class, 'index'])->name('index');
    Route::resource('users', UserController::class);
    Route::get('categories/slug', [CategoryController::class, 'generateSlug'])->name('categories.slug');
    Route::resource('categories', CategoryController::class);
    Route::get('products/slug', [ProductController::class, 'generateSlug'])->name('products.slug');
    Route::resource('products', ProductController::class);
    Route::resource('stocks', StockController::class);
    Route::resource('attributes', AttributeController::class);
    Route::resource('coupons', CouponController::class);

    //orders
    Route::post('/orders/{order}/status', [OrderController::class, 'UpdateStatus'])->name('orders.status');
    Route::post('/orders/{order}/products', [OrderController::class, 'AddProduct'])->name('orders.products');
    Route::delete('/orders/{order}/products', [OrderController::class, 'removeProduct'])->name('orders.removeProducts');
    Route::get('/orders/{order}/{orderid}/quantity', [OrderController::class, 'editQuantity'])->name('orders.quantity.edit');
    Route::post('/orders/{order}/{orderid}/quantity', [OrderController::class, 'updateQuantity'])->name('orders.quantity.update');

    Route::resource('orders', OrderController::class)->except(['destroy']);
    Route::resource('sliders', SliderController::class);

    Route::resource('carts', CartController::class);
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Order extends Model
{
    use HasFactory;

    // const STATUS = ['Pending', 'Confirmed', 'Cancelled', 'Delivering', 'Completed', 'Return', 'Refund'];

    protected $guarded = [];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    // public function product(): HasMany
    // {
    //     return $this->hasMany(Product::class);
    // }

    public function products(): BelongsToMany
    {
        return $this->belongsToMany(Product::class)
            ->withPivot(['id', 'quantity', 'unit_price']);
    }

    // Another Way For Pivot 
    // public function orderproduct(): HasMany
    // {
    //     return $this->hasMany(OrderProduct::class);
    // }

    public function coupon(): BelongsTo
    {
        return $this->belongsTo(Coupon::class);
    }

    public function getTotalAttribute()
    {
        $total = 0;

        foreach ($this->products as $item) {
            $total = $total + ($item->pivot->unit_price * $item->pivot->quantity);
        }

        return $total;
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use App\Models\Order;
use Illuminate\View\View;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;
use App\Models\OrderProduct;
use App\Models\Product;
use Illuminate\Http\RedirectResponse;

class OrderController extends Controller
{
    protected $payment_methods = [
        'Cash on delivery',
        'e-Sewa',
    ];

    protected $status = [
        'Pending', 'Confirmed', 'Cancelled', 'Delivering', 'Completed', 'Return', 'Refund',
    ];

    public function index(): View
    {
        $orders = Order::with(['user', 'products'])->paginate(12);

        return view('admin.orders.index', compact('orders'));
    }

    public function create(): View
    {
        $payment_methods = $this->payment_methods;
        // $status = Order::STATUS;
        $status = $this->status;
        $products = Product::all();

        $users = User::all();

        return view('admin.orders.create', compact('payment_methods', 'status', 'users', 'products'));
    }

    public function store(Request $request): RedirectResponse
    {

        $data = $request->validate([
            'user_id'           => ['required', 'exists:users,id'],
            'shipping_name'     => ['required'],
            'shipping_address'  => ['required'],
            'shipping_city'     => ['required'],
            'shipping_street'   => ['required'],
            'shipping_phone'    => ['required'],
            'billing_name'      => ['required'],
            'billing_address'   => ['required'],
            'billing_city'      => ['required'],
            'billing_street'    => ['required'],
            'billing_phone'     => ['required'],
            'payment_method'    => ['required', Rule::in($this->payment_methods)],
            'subtotal'          => ['required'],
            'discount'          => ['nullable'],
            'total'             => ['required'],
        ]);

        Order::create($data);

        return redirect()->route('admin.orders.index')->with('success', 'Order Recieved Successfully ');
    }

    public function show(Order $order): View
    {
        $status = $this->status;
        $products = Product::all();

        // $total = 0;

        // foreach ($order->products as $item) {
        //     $total = $total + ($item->pivot->unit_price * $item->pivot->quantity);
        // }

        return view('admin.orders.show', compact('order', 'status', 'products'));
    }

    public function edit(Order $order): View
    {
        $payment_methods = $this->payment_methods;
        $status = $this->status;

        $products = Product::all();
        $users = User::all();

        return view('admin.orders.edit', compact('order', 'payment_methods', 'status', 'users', 'products'));
    }

    public function update(Request $request, Order $order): RedirectResponse
    {
        // $status = Order::STATUS;

        $data = $request->validate([
            'user_id'           => ['required', 'exists:users,id'],
            'shipping_name'     => ['required'],
            'shipping_address'  => ['required'],
            'shipping_city'     => ['required'],
            'shipping_street'   => ['required'],
            'shipping_phone'    => ['required'],
            'billing_name'      => ['required'],
            'billing_address'   => ['required'],
            'billing_city'      => ['required'],
            'billing_street'    => ['required'],
            'billing_phone'     => ['required'],
            'payment_method'    => ['required', Rule::in($this->payment_methods)],
            'subtotal'          => ['required'],
            'discount'          => ['nullable'],
            'total'             => ['required'],
            'status'            => ['required', Rule::in($this->status)],
            'remarks'           => ['nullable'],
        ]);

        $order->update($data);

        return redirect()->route('admin.orders.index')->with('success', 'Order Updated Successfully ');
    }

    public function UpdateStatus(Request $request, Order $order)
    {
        $data = $request->validate([
            'status'    =>  ['required', Rule::in($this->status)],
        ]);

        $order->update($data);

        return redirect()->route('admin.orders.show', $order)->with('success', 'Status Updated Successfully');
    }

    public function AddProduct(Request $request, Order $order)
    {
        $data = $request->validate([
            'product_id'    =>  ['required', 'exists:products,id'],
            'quantity'      =>  ['required', 'integer', 'min:0'],
        ]);

        $product = Product::find($request->product_id);
        $price = $product->on_sale ? $product->sale_price : $product->price;

        $quantityCheck = OrderProduct::where('product_id', $request->product_id)

            ->where('order_id', $order->id)
            ->first();

        if ($quantityCheck) {
            $quantityCheck->update(['quantity' => $quantityCheck->quantity + $request->quantity]);
        } else {
            OrderProduct::create([
                'order_id'      =>  $order->id,
                'product_id'    =>  $request->product_id,
                'quantity'      =>  $request->quantity,
                'unit_price'    =>  $price,
            ]);
        }

        return redirect()->route('admin.orders.show', $order)->with('success', 'Product Added To Order Successfully');
    }

    public function removeProduct(Request $request, Order $order)
    {
        $request->validate([
            'order_product_id'  =>  ['required', 'exists:order_product,id'],
        ]);

        $orderproduct = OrderProduct::find($request->order_product_id);

        if ($orderproduct->order_id != $order->id) {
            return redirect()->route('admin.orders.show', $order)->with('error', 'Product could not be removed as it belongs to another order');
        }

        $orderproduct->delete();

        return redirect()->route('admin.orders.show', $order)->with('success', 'Product Removed From The Order Successfully');
    }

    public function editQuantity(Order $order, $orderid)
    {
        $orderproduct = OrderProduct::findOrFail($orderid);
        return view('admin.orders.quantity', compact('order', 'orderproduct'));
    }

    public function updateQuantity(Request $request, Order $order, $orderid)
    {
        $orderproduct = OrderProduct::findOrFail($orderid);

        $data = $request->validate([
            'quantity'   =>  ['required', 'integer', 'min:0'],
        ]);

        $orderproduct->update($data);

        return redirect()->route('admin.orders.show', $order)->with('success', 'Product Quantity Updated Successfully');
    }
}

resources/views/admin/orders/create.blade.php
@extends('adminlte::page')

@section('title','Create Order')

@section('content')

<x-alert/>

<div class="card">
    <div class="card-header">
        <h3 class="card-title text-bold" style="font-size: 1.3rem; line-height: 1.5;">
            Create Order
        </h3>

        <div class="card-tools">
            <a href="{{ route('admin.orders.index') }}" class="btn-sm btn-primary">
                <i class="fas fa-fw fa-arrow-left mr-1"></i>
                <span>Show All Orders</span>
            </a>
        </div>
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route('admin.orders.store') }}" enctype="multipart/form-data" >

            @csrf

            {{-- <x-input
            field="user_id"
            text="User"
            type="select"
            :options="$users"
            :required="true"
            /> --}}

        <div class="form-group">
            <label for="user_id">User</label>
            <select name="user_id" id="user_id" class="form-control @error('user_id')
                is invalid
            @enderror">

            <option value="">Select a User...</option>

                @foreach ($users as $user )
                    <option 
                    value="{{ $user->id }}"
                    @if ( old('user_id') == $user->id )
                        selected
                    @endif>
                    {{ $user->name }}
                    </option>
                @endforeach
                @error('user_id')
                    <small class="form-text text-danger">
                    {{ $message }}
                    </small>
                @enderror
            </select>
            @error('user_id')
                <small class="form-text text-danger">
                {{ $message }}
                </small>
            @enderror
        </div>

        <div class="form-group">
            <label for="product_id">Product</label>
            <select name="product_id" id="product_id" class="form-control @error('product_id')
                is invalid
            @enderror">
        <option value="">Select a Product...</option>

                @foreach ($products as $product )
                    <option 
                    value="{{ $product->id }}"
                    @if ( old('product_id') == $product->id )
                        selected
                    @endif>
                    {{ $product->name }}
                    </option>
                    @error('product_id')
                    <small class="form-text text-danger">
                    {{ $message }}
                    </small>
                    @enderror
                @endforeach
            </select>
            @error('product_id')
                <small class="form-text text-danger">
                {{ $message }}
                </small>
            @enderror
        </div>

        <x-input
        field="shipping_name"
        text="Enter Shipping Name"
        />

         <x-input
        field="shipping_address"
        text="Enter Shipping Address"
        />

        <x-input
        field="shipping_city"
        text="Enter Shipping City"
        />

        <x-input
        field="shipping_street"
        text="Enter Shipping Street"
        />

         <x-input
        field="shipping_phone"
        text="Enter Shipping Phone Number"
        type="number"
        />

        <x-input
        field="billing_name"
        text="Enter Billing Name"
        />

        <x-input
        field="billing_address"
        text="Enter Billing Address"
        />

        <x-input
        field="billing_city"
        text="Enter Billing City"
        />

        <x-input
        field="billing_street"
        text="Enter Billing Street"
        />

         <x-input
        field="billing_phone"
        text="Enter Billing Phone Number"
        type="number"
        />


        <div class="form-group">
            <label for="payment_method">Payment Method</label>
            <select name="payment_method" id="payment_method" class="form-control 
            @error('payment_method')
                is invalid
            @enderror">
                <option value="payment_method">Select the payment method...</option>
                @foreach ($payment_methods as $payment_method )
                    <option 
                    value="{{ $payment_method }}"
                    @if ( old('payment_method') == $payment_method )
                        selected
                    @endif>
                    {{ $payment_method }}
                    </option>
                @endforeach
            </select>
            @error('payment_method')
                <small class="form-text text-danger">
                {{ $message }}
                </small>
            @enderror
        </div>
        
        <x-input
        field="subtotal"
        text="Subtotal"
        type="number"
        />

        <x-input
        field="discount"
        text="Discount"
        type="number"
        />

        <x-input
        field="total"
        text="Total"
        type="number"
        />

        <div class="form-group">
            <label for="status">Status</label>
            <select name="status" id="status" class="form-control @error('status')
                is invalid
            @enderror">
            <option value="status">What is the status of the order ?</option>
                @foreach ($status as $stat )
                    <option 
                    value="{{ $stat }}"
                    @if ( old('stat') == $stat )
                        selected
                    @endif>
                    {{ $stat }}
                    </option>
                @endforeach
                @error('status')
                <small class="form-text text-danger">
                {{ $message }}
                </small>
            @enderror
            </select>
            @error('status')
                <small class="form-text text-danger">
                {{ $message }}
                </small>
            @enderror
        </div>


        <button type="submit" class="btn-sm btn-primary">
            <i class="fas fa-fw fa-save mr-2"></i>
            <span>Save</span>
        </button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/orders/index.blade.php
@extends('adminlte::page')

@section('title', 'Orders List')

@section('content')

<x-alert/>

    <div class="card">
        <div class="card-header">

            <h3 class="card-title text-bold" style="font-size: 1.3rem; line-height: 1.5">Orders</h3>
            <div class="card-tools">
              <a href="{{route('admin.orders.create')}}" class="btn-sm btn-primary" >Add Order</a>
            </div>
            
        </div>
        <div class="card-body p-0">

            @if (count($orders) > 0)              
           
            <table class="table table-bordered table-striped">
                <thead class="thead-dark bg-info">
                    <tr>
                        <td>ID</td>
                        <td>User Name</td>
                        <td>Total Amount</td>
                        <td>Status</td>
                        <td>Total Amount</td>
                        <td>Remarks</td>
                        <td>Actions</td>
                    </tr>
                </thead>

                <tbody>
                    
                    @foreach ($orders as $order )

                    <tr>
                        <td>{{ $order->id }}</td>
                        <td>
                                <a href="{{ route('admin.users.show',$order->user_id)}}">
                                {{ $order->user->name }}
                                </a>
                        </td>
                        {{-- <td>
                            @if ($order->product_id)
                                <a href="{{ route('admin.products.show',$order->product_id)}}">
                                {{ $order->products->name }}
                                </a>
                            @endif
                        </td> --}}
                        <td>{{ $order->total }}</td>
                        <td>{{ $order->status }}</td>
                        <td>Rs. {{ $order->total }}</td>
                        <td>{{ $order->remarks}}</td>
                        <td>
                            <a 
                                href="{{ route('admin.orders.show', $order->id) }}" 
                                class="btn-sm btn-primary mr-2">
                                Show Details
                            </a>

                            <a 
                                href="{{ route('admin.orders.edit', $order->id) }}" 
                                class="btn-sm btn-secondary mr-2">
                                Edit order
                            </a>                                                
                        </td>
                    </tr>
                    
                    @endforeach
                    
                </tbody>
            </table>
            
            @else

            <div class="alert alert-warning mb-0 text-center">
                No more orders available !
            </div>

            @endif
            
        </div>
        @if ($orders->perpage() < $orders->total() )
            <div class="card-footer">
                {{ $orders->links() }}
            </div>
        @endif
    </div>
@endsection

resources/views/admin/orders/quantity.blade.php
@extends('adminlte::page')

@section('title','Update Quantity')

@section('content')

<x-alert/>

<div class="card">
    <div class="card-header">
        <h3 class="card-title text-bold" style="font-size: 1.3rem; line-height: 1.5;">
            Update Quantity
        </h3>

        <div class="card-tools">
            <a href="{{ route('admin.orders.show', $order) }}" class="btn-sm btn-primary">
                <i class="fas fa-fw fa-arrow-left mr-1"></i>
                <span>Show Order</span>
            </a>
        </div>
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route('admin.orders.quantity.update',[$order->id,$orderproduct->id]) }}" enctype="multipart/form-data" >

            @csrf

            <div class="form-group">
                <label for="product">Product</label>
                <input type="text" class="form-control" value="{{ $orderproduct->product->name }}" disabled>
            </div>

            <x-input
            field="quantity"
            type="number"
            text="Quantity"
            :current="$orderproduct->quantity"
            />


        <button type="submit" class="btn-sm btn-primary">
            <i class="fas fa-fw fa-save mr-2"></i>
            <span>Save</span>
        </button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/orders/show.blade.php
@extends('adminlte::page')

@section('title','Order Details')

@section('content')

<x-alert/>

<x-delete/>

<div class="card">
    <div class="card-header">
        <h3 class="card-title text-bold" style="font-size: 1.3rem; line-height: 1.5;">
            Order Details
        </h3>

        <div class="card-tools">
             <form action="{{ route('admin.orders.status', $order )}}" method="POST" style="display: inline-block" class="mr-4">

                @csrf

                <div class="input-group">
                    <select name="status" id="status" class="form-control" style="min-width: 150px">
                        @foreach ($status as $stat )
                            <option value="{{ $stat }}" 
                                @if ($order->status == $stat)
                                    selected
                                @endif>
                                {{ $stat }}
                            </option>
                        @endforeach
                    </select>
                    <div class="input-group-append">
                        <button class="btn btn-info" type="submit" id="button-addon2">Update Status</button>
                    </div>
                </div>
            </form>

            <a href="{{ route('admin.orders.index') }}" class="btn-sm btn-primary">
                <i class="fas fa-fw fa-arrow-left mr-1"></i>
                <span>Show All Orders</span>
            </a>
        </div>
    </div>
    
    <div class="card-body p-0">
        <table class="table table-bordered">
            <tr>
                <th style="width: 15%;">Order ID</th>
                <td>{{ $order->id }}</td>
            </tr>

            <tr>
                <th>User Name</th>
                <td>
                    @if ($order->user_id)
                        <a href="{{ route('admin.users.show',$order->user_id)}}">
                        {{ $order->user->name }}
                        </a>
                    @endif
                </td>
            </tr>
            
        </table>
    </div>

    <div class="card-body">
        <form action="{{ route('admin.orders.products', $order) }}" method="POST" enctype="multipart/form-data">
             @csrf

            <div class="row">
                <div class="col-12 col-md-8">
                    <div class="form-group">
                        <label for="product_id">Product</label>
                        <select name="product_id" id="product_id" class="form-control @error('product_id')
                            is invalid
                        @enderror">
                            <option value="">Select a Product...</option>

                            @foreach ($products as $product )
                                <option 
                                value="{{ $product->id }}"
                                @if ( old('product_id') == $product->id )
                                    selected
                                @endif>
                                {{ $product->name }}
                                </option>
                                @error('product_id')
                                <small class="form-text text-danger">
                                {{ $message }}
                                </small>
                                @enderror
                            @endforeach
                        </select>
                        @error('product_id')
                            <small class="form-text text-danger">
                            {{ $message }}
                            </small>
                        @enderror
                    </div>
                </div>

                <div class="col-12-col-md-2 mr-4">
                    <x-input
                    field="quantity"
                    text="Quantity"
                    type="number"
                    :current="old('quantity') ?? 1"
                    />
                </div>

                <div class="col-12-col-md-2 pt-2">
                    <button type="submit" class="btn-sm btn-primary mt-4">
                        <i class="fas fa-fw fa-save mr-2"></i>
                        <span>Save</span>
                    </button>
                </div>
            </div>
            
        </form>
    </div>

    <div class="card-body p-0">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>SN</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>Total Price</th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody>

                {{-- @dd($order) --}}
                @foreach ($order->products as $item )
                    <tr>
                        <td>{{ $loop->index +1 }}</td>
                        <td>{{ $item->name }}</td>
                        <td>{{ $item->pivot->quantity }}</td>
                        <td>Rs. {{ $item->pivot->unit_price }}</td>
                        <td>Rs. {{ $item->pivot->unit_price * $item->pivot->quantity }}</td>
                        <td>
                            <a href="{{ route('admin.orders.quantity.edit', [$order, $item->pivot->id])}}" class="btn btn-sm btn-primary">Edit</a>

                            <a href="#!" onclick="confirmDelete({{ $item->pivot->id }})" class="btn btn-sm btn-danger">Delete</a>

                            <form id="delete-form-{{ $item->pivot->id }}" action="{{ route('admin.orders.removeProducts', $order) }}" method="POST">
                                @csrf @method('DELETE')
                                <input type="hidden" name="order_product_id" value="{{ $item->pivot->id }}">
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>

            <tr>
                <th colspan="4" style="text-align: right">Total</th>
                <td><b>Rs. {{ $order->total }}</b></td>
                <td></td>
            </tr>
        </table>
    </div>

    <div class="card-body p-0">
        <table class="table table-bordered">
            <tr>
                <th style="width: 15%;">Shipping To </th>
                <td>{{ $order->shipping_name }}</td>
            </tr>
            
            <tr>
                <th>Shipping Address </th>
                <td>{{ $order->shipping_address }}</td>
            </tr>

            <tr>
                <th>Shipping City </th>
                <td>{{ $order->shipping_city }}</td>
            </tr>

            <tr>
                <th>Shipping Street </th>
                <td>{{ $order->shipping_street }}</td>
            </tr>

            <tr>
                <th>Shipping Phone Number</th>
                <td>{{ $order->shipping_phone }}</td>
            </tr>

            <tr>
                <th>Billed To </th>
                <td>{{ $order->billing_name }}</td>
            </tr>

            <tr>
                <th>Billing Address </th>
                <td>{{ $order->billing_address }}</td>
            </tr>

            <tr>
                <th>Billing City </th>
                <td>{{ $order->billing_city }}</td>
            </tr>

            <tr>
                <th>Billing Street </th>
                <td>{{ $order->billing_street }}</td>
            </tr>

            <tr>
                <th>Billing City </th>
                <td>{{ $order->billing_city }}</td>
            </tr>

            <tr>
                <th>Billing Phone Number </th>
                <td>{{ $order->billing_phone }}</td>
            </tr>

            <tr>
                <th>Payment Method</th>
                <td>{{ $order->payment_method }}</td>
            </tr>
            
            <tr>
                <th>Subtotal</th>
                <td>{{ $order->subtotal }}</td>
            </tr>

            <tr>
                <th>Discount</th>
                <td>{{ $order->discount}}</td>
            </tr>

            <tr>
                <th>Total Amount</th>
                <td><b>Rs. {{ $order->total }}</b></td>
            </tr>

            <tr>
                <th>Customer Remarks</th>
                <td>{{ $order->remarks }}</td>
            </tr>

            <tr>
                <th>Placed</th>
                <td>{{ $order-> created_at }}</td>
            </tr>

            <tr>
                <th>Updated</th>
                <td>{{ $order-> updated_at }}</td>
            </tr>
        </table>
    </div>
</div>
@endsection