routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\StockController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\AttributeController;
use App\Http\Controllers\Admin\CartController;
use App\Http\Controllers\Admin\SliderController;

Route::get('/', [SiteController::class, 'index'])->name('index');
Route::get('/products/{product}', [SiteController::class, 'product'])->name('product');
Route::get('/cart', [SiteController::class, 'cart'])->name('cart');
Route::get('/add-to-cart/{product}', [SiteController::class, 'addToCart'])->name('add.to.cart')->middleware('auth');
Route::patch('update-cart', [SiteController::class, 'update'])->name('update.cart');
Route::delete('remove-from-cart', [SiteController::class, 'remove'])->name('remove.from.cart');


Route::get('/home', [SiteController::class, 'home'])->name('home')->middleware('auth');

Route::get('/search', [\App\Http\Controllers\SiteController::class, 'search'])->name('search');

// Route::group(
//     [
//         'middleware' => ['auth', 'admin'],
//         'name' => 'admin.',
//         'prefix' => 'admin'
//     ],
//     function () {
//         Route::get('/', [AdminController::class, 'index'])->name('index');
//         Route::resource('users', [UserController::class]);
//     }
// );
// 'auth', 'admin'
Route::middleware(['auth', 'admin'])->name('admin.')->prefix('admin')->group(function () {
    Route::get('/', [AdminController::class, 'index'])->name('index');
    Route::resource('users', UserController::class);
    Route::get('categories/slug', [CategoryController::class, 'generateSlug'])->name('categories.slug');
    Route::resource('categories', CategoryController::class);
    Route::get('products/slug', [ProductController::class, 'generateSlug'])->name('products.slug');
    Route::resource('products', ProductController::class);
    Route::resource('stocks', StockController::class);
    Route::resource('attributes', AttributeController::class);
    Route::resource('coupons', CouponController::class);

    //orders
    Route::post('/orders/{order}/status', [OrderController::class, 'UpdateStatus'])->name('orders.status');
    Route::post('/orders/{order}/products', [OrderController::class, 'AddProduct'])->name('orders.products');
    Route::delete('/orders/{order}/products', [OrderController::class, 'removeProduct'])->name('orders.removeProducts');
    Route::get('/orders/{order}/{orderid}/quantity', [OrderController::class, 'editQuantity'])->name('orders.quantity.edit');
    Route::post('/orders/{order}/{orderid}/quantity', [OrderController::class, 'updateQuantity'])->name('orders.quantity.update');

    Route::resource('orders', OrderController::class)->except(['destroy']);
    Route::resource('sliders', SliderController::class);

    Route::resource('carts', CartController::class);
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use PhpParser\Node\Expr\Cast\String_;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'slug', 'media_id', 'category_id', 'description'];

    public function parentCategory(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function childCategory(): HasMany
    {
        return $this->hasMany(Category::class, 'category_id', 'id');
    }

    public function product(): HasMany
    {
        return $this->hasMany(Product::class, 'products', 'category_id');
    }

    public function media(): BelongsTo
    {
        return $this->belongsTo(Media::class);
    }


    // Accesser function

    public function getImageAttribute(): ?String
    {
        if ($this->media_id && $this->media) {
            return "/storage/" . $this->media->path;
        }
        return null;
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use Illuminate\View\View;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Services\MediaService;
use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{

    public function index(): View
    {
        $categories = Category::paginate(12);
        return view('admin.categories.index', compact('categories'));
    }


    public function create(): View
    {
        $categories = Category::all();
        return view('admin.categories.create', compact('categories'));
    }


    public function store(Request $request): RedirectResponse
    {
        $request['slug'] = Str::slug($request['slug']);

        $data = $request->validate([
            'name'          => ['required'],
            'slug'          => ['required', 'unique:categories,slug'],
            'image'         => ['nullable', 'image', 'mimes:png,jpg,gif'],
            'category_id'   => ['nullable', 'exists:categories,id'],
            'description'   => ['nullable'],
        ]);

        unset($data['image']);

        if ($request->hasFile('image')) {
            $data['media_id'] = (new MediaService)->upload($request->file('image'), 'categories');
        }

        Category::create($data);

        return redirect()->route('admin.categories.index')->with('success', 'Category added Successfully!');
    }


    public function show(Category $category): View
    {
        return view('admin.categories.show', compact('category'));
    }


    public function edit(Category $category): View
    {
        $categories = Category::where('id', '!=', $category->id)->get();

        return view('admin.categories.edit', compact('category', 'categories'));
    }

    public function update(Request $request, Category $category): RedirectResponse
    {
        $request['slug'] = Str::slug($request['slug']);

        $data = $request->validate([
            'name'          => ['required'],
            'slug'          => ['required', 'unique:categories,slug,' . $category->id],
            'image'         => ['nullable', 'image', 'mimes:png,jpg,gif'],
            'category_id'   => ['nullable', 'exists:categories,id'],
            'description'   => ['nullable'],
        ]);

        unset($data['image']);

        if ($request->hasFile('image')) {

            if ($category->media_id && $category->media) {
                Storage::delete('public/' . $category->media->path);
            }

            $data['media_id'] = (new MediaService)->upload($request->file('image'), 'categories');
        }

        $category->update($data);

        return redirect()->route('admin.categories.index')->with('success', 'Category Updated Successfully!');
    }


    public function destroy(Category $category): RedirectResponse
    {
        if ($category->media_id && $category->media) {
            Storage::delete('public/' . $category->media->path);
        }

        $category->delete();

        return redirect()->route('admin.categories.index')->with('success', 'Category Deleted Successfully!');
    }

    public function generateSlug(Request $request): string
    {
        if (empty($request->title)) {
            return "";
        }

        $title = Str::slug($request->title);
        return $this->checkAndGenerateSlug($title, 0);
    }

    public function checkAndGenerateSlug(string $title, int $number = 0): string
    {
        if ($number > 0) {
            $new_title = $title . "-" . $number;
        }

        if (Category::where('slug', $new_title ?? $title)->first()) {
            return $this->checkAndGenerateSlug($title, $number + 1);
        }

        return $new_title ?? $title;
    }
}

resources/views/admin/categories/create.blade.php
@extends('adminlte::page')

@section('title','Create Category')

@push('js')
    <script>

        $('#name').keyup(function() {

            let title = document.getElementById('name').value;

            if (title == ''){
                $('#slug-suggestion').hide();
                return;
            }

            $.ajax({

                url: "{{ route('admin.categories.slug') }}",
                data: { title: title },

                success: function(result){

                $('#slug-suggestion').slideDown();
                $('#slug-value').text(result);
                
                }
            });

        });

        $('#slug-value').on('click', function(e){
            e.preventDefault();

            $('#slug').val($('#slug-value').text());
        });
        
    </script>
@endpush

@section('content')

<x-alert/>

<div class="card">
    <div class="card-header">
        <h3 class="card-title text-bold" style="font-size: 1.3rem; line-height: 1.5;">
            Create New Category
        </h3>

        <div class="card-tools">
            <a href="{{ route('admin.categories.index') }}" class="btn-sm btn-primary">
                Show All Categories
            </a>
        </div>
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route('admin.categories.store') }}" enctype="multipart/form-data" >

            @csrf

        <x-input
        field="name"
        text="Name"
        />


        <x-input
        field="slug"
        text="Slug"
        />

        <div class="form-text mb-3 text-muted" style="display: none" id="slug-suggestion" >
            Suggested Slug: <a href="#" id="slug-value"></a> 
        </div>


        <div class="form-group">
            <label for="category_id">Parent Category</label>
            <select name="category_id" id="category_id" class="form-control @error('category_id')
                is invalid
            @enderror">

            <option value="">Select a parent category...</option>

                @foreach ($categories as $cat )
                    <option 
                    value="{{ $cat->id }}"
                    @if ( old('category_id') == $cat->id )
                        selected
                    @endif>
                    {{ $cat->name }}
                    </option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="image">Upload Category Picture</label>
            <input type="file" name="image" id="image">
        </div>

        <button type="submit" class="btn-sm btn-primary">
            <i class="fas fa-fw fa-save mr-2"></i>
            <span>Save</span>
        </button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('adminlte::page')

@section('title','Update Category')

@push('js')

<script>

    $('#name').keyup(function() {

        let title = document.getElementById('name').value;

        if(title == ''){
            $('#slug-suggestion').hide();
            return;
        }

        $.ajax({
            url: "{{ route('admin.categories.slug') }}",
            data: { title : title },
            
            success:function(result){
                $('#slug-suggestion').slideDown();
                $('#slug-value').text(result);
            }

        });
    });

    $('#slug-value').on('click', function(e) {
        
        e.preventDefault();

        $('#slug').val($('#slug-value').text());
    });

</script>

@endpush

@section('content')

<x-alert/>

<div class="card">
    <div class="card-header">
        <h3 class="card-title text-bold" style="font-size: 1.3rem; line-height: 1.5;">
            Update Category
        </h3>

        <div class="card-tools">
            <a href="{{ route('admin.categories.index') }}" class="btn-sm btn-primary">
                Show All Categories
            </a>
        </div>
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route('admin.categories.update',$category->id) }}" enctype="multipart/form-data" >

            @csrf
            @method('PUT')
        <x-input
        field="name"
        text="Name"
        :current="$category->name"
        />

        <x-input
        field="slug"
        text="Slug"
        :current="$category->slug"
        />

        <div class="form-text mb-3 text-muted" style="display: none;" id="slug-suggestion">
            Suggested Slug: <a href="#" id="slug-value"></a>
        </div>

        <div class="form-group">
            <label for="category_id">Parent Category</label>
            <select name="category_id" id="category_id" class="form-control @error('category_id')
                is invalid
            @enderror">
            
            <option value="">Select a parent category...</option>

                @foreach ($categories as $cat )
                    <option 
                    value="{{ $cat->id }}"
                    @if ( $category->category_id == $cat->id )
                        selected
                    @endif>
                    {{ $cat->name }}
                    </option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="image">Upload Category Picture</label>
            <input type="file" name="image" id="image">
        </div>

       @if ($category->image)
            <div class="mb-2 form-group">
                <label for="image">Current Category Picture</label>
                <img src="{{ $category->image }}" class="ml-2" height="120px" width="140px" alt="Category Picture">
            </div>
        @endif

        <button type="submit" class="btn-sm btn-primary">
            <i class="fas fa-fw fa-save mr-2"></i>
            <span>Save</span>
        </button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('adminlte::page')

@section('title', 'Category List')

@section('content')

<x-alert/>
<x-delete/>

    <div class="card">
        <div class="card-header">

            <h3 class="card-title text-bold" style="font-size: 1.3rem; line-height: 1.5">Categories</h3>
            <div class="card-tools">
              <a href="{{route('admin.categories.create')}}" class="btn-sm btn-primary" >Add New Category</a>
            </div>
            
        </div>
        <div class="card-body p-0">

            @if (count($categories) > 0)              
           
            <table class="table table-bordered table-striped">
                <thead class="thead-dark bg-info">
                    <tr>
                        <td>ID</td>
                        <td>Category Name</td>
                        <td>Slug</td>
                        <td>Parent</td>
                        <td>Actions</td>
                    </tr>
                </thead>

                <tbody>
                    
                    @foreach ($categories as $category )

                    <tr>
                        <td>{{ $category->id }}</td>
                        <td>{{ $category->name }}</td>
                        <td>{{ $category->slug }}</td>
                        <td>
                            @if ($category->category_id)
                                <a href="{{ route('admin.categories.show',$category->category_id)}}">
                                    {{ $category->parentCategory->name }}
                                </a>
                            @endif    
                        </td>

                        <td>
                            <a 
                                href="{{ route('admin.categories.show', $category->id) }}" 
                                class="btn-sm btn-primary mr-2">
                                Show Details
                            </a>

                            <a 
                                href="{{ route('admin.categories.edit', $category->id) }}" 
                                class="btn-sm btn-secondary mr-2">
                                Edit category
                            </a>
                            
                            <a href="#" onclick="confirmDelete({{ $category->id }})" class="btn-sm btn-danger" > Delete 
                            </a>

                            <form id="delete-form-{{ $category->id }}" action="{{ route('admin.categories.destroy', $category) }}" method="POST">

                            @csrf    
                            @method('DELETE')

                            </form>
                            
                        </td>
                    </tr>
                    
                    @endforeach
                    
                </tbody>
            </table>
            
            @else

            <div class="alert alert-warning mb-0 text-center">
                No more categories available !
            </div>

            @endif
            
        </div>
        @if ($categories->perpage() < $categories->total() )
            <div class="card-footer">
                {{ $categories->links() }}
            </div>
        @endif
    </div>
@endsection

resources/views/admin/categories/show.blade.php
@extends('adminlte::page')

@section('title','Category Details')

@section('content')

<x-alert/>

<div class="card">
    <div class="card-header">
        <h3 class="card-title text-bold" style="font-size: 1.3rem; line-height: 1.5;">
            Category Details
        </h3>

        <div class="card-tools">
            <a href="{{ route('admin.categories.index') }}" class="btn-sm btn-primary">
                Show All Categories
            </a>
        </div>
    </div>
    
    <div class="card-body p-0">
        <table class="table">
            <tr>
                <th style="width: 15%;">ID</th>
                <td>{{ $category->id }}</td>
            </tr>
            
            @if ($category->image)
            <tr>
                <th>Category Picture</th>
                <td>                    
                    <img src="{{ $category->image }}" height="160px" width="200px" alt="Category Picture">                                                        
                </td>
            </tr>
            @endif 

            <tr>
                <th>Name</th>
                <td>{{ $category->name }}</td>
            </tr>

            <tr>
                <th>Slug</th>
                <td>{{ $category->slug }}</td>
            </tr>

            <tr>
                <th>Parent Category</th>
                <td>
                    @if ($category->category_id)
                        <a href="{{ route('admin.categories.show',$category->category_id)}}">
                            {{ $category->parentCategory->name }}
                        </a>
                    @endif
                </td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ $category->description}}</td>
            </tr>
            
            <tr>
                <th>Created</th>
                <td>{{ $category-> created_at }}</td>
            </tr>
            
        </table>
    </div>
</div>
@endsection